# Generated by Django 4.1.7 on 2023-03-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('curr_availability', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
