# Generated by Django 4.1.7 on 2023-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_remove_test_appoitmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='appoitmentID',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='status',
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatmentName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
