# Generated by Django 4.1.7 on 2023-03-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Emergency')], null=True),
        ),
    ]
