# Generated by Django 4.1.7 on 2023-03-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_appointment_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='emailID',
            field=models.EmailField(max_length=240, null=True),
        ),
    ]
