# Generated by Django 4.1.7 on 2023-03-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_doctor_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='emailID',
        ),
    ]
