# Generated by Django 4.1.7 on 2023-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_remove_room_type_alter_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='curr_availability',
            field=models.IntegerField(),
        ),
    ]
