# Generated by Django 4.1.7 on 2023-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_alter_room_curr_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='curr_availability',
            field=models.PositiveIntegerField(),
        ),
    ]
