# Generated by Django 4.1.7 on 2023-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_alter_room_curr_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
